name: Analyze Images on Pull Request

on:
  pull_request:
    branches: [ main ]
    paths:
      - "images/**"

jobs:
  analyze-images:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      S3_PREFIX: ${{ secrets.S3_PREFIX }}
      DYNAMODB_TABLE_BETA: ${{ secrets.DYNAMODB_TABLE_BETA }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install boto3

      - name: Run Rekognition analysis
        run: python analyze_image.py